// ======================== TASK TEMPLATES - ~1000 UNIQUE PROMPTS ========================
// Each prompt has jp (Japanese for TTS) and en (Japanese-accented English for display)

const TASK_TEMPLATES = [
  { type: 'draw', prompts: [
    // --- Animals ---
    { jp: 'お花を描いてくれない？どんな花でもいいよ！', en: 'draw me flower ne? any kind is fine desu!' },
    { jp: '虹を描いて！この世界みたいにカラフルなやつ！', en: 'draw rainbow! colorful like this sekai ne!' },
    { jp: '私の顔を描いてみて！可愛く描いてね！', en: 'draw Pippin face desu! make it kawaii ne!' },
    { jp: 'キノコを描いて！踊ってるやつがいい！', en: 'draw mushroom! dancing one onegai!' },
    { jp: '星空を描いてくれる？きらきらしてるやつ！', en: 'draw starry sky ne? kirakira sparkly one!' },
    { jp: 'バスタブに乗ったユニコーンを描いて。つまり私。', en: 'draw unicorn in bathtub desu. that is me.' },
    { jp: 'ドラゴンを描いて！私の友達になるかも！', en: 'draw dragon desu! maybe become Pippin tomodachi!' },
    { jp: 'ピザを描いて！めっちゃお腹空いてる！', en: 'draw pizza ne! Pippin meccha hungry desu!' },
    { jp: '宇宙人を描いて！この世界にいそうじゃない？', en: 'draw alien desu! they probably live here desho?' },
    { jp: '猫を描いて！猫大好き！ユニコーンだけど！', en: 'draw neko ne! Pippin love cats! even though unicorn desu!' },
    { jp: 'ロケットを描いて！月まで飛びたい！', en: 'draw rocket desu! Pippin want fly to moon ne!' },
    { jp: 'お城を描いて！私のお城！ピピン城！', en: 'draw castle ne! Pippin castle! Pippin-jou desu!' },
    { jp: '自分の顔を描いて！どんな顔してるの？', en: 'draw YOUR face ne! what do you look like desho?' },
    { jp: 'おにぎりを描いて！三角のやつ！', en: 'draw onigiri desu! triangle one ne!' },
    { jp: 'この川を描いて！虹色にしてね！', en: 'draw this river ne! make it rainbow iro desu!' },
    { jp: '一番好きな動物を描いて！私以外で！', en: 'draw favorite animal ne! other than Pippin desu!' },
    { jp: 'ゾンビを描いて！可愛いゾンビね！怖いのはダメ！', en: 'draw zombie desu! kawaii zombie ne! scary one dame!' },
    { jp: '自分の夢を描いて！どんな夢見るの？', en: 'draw your yume ne! what do you dream about desho?' },
    { jp: 'タコを描いて！足が８本あるやつ！', en: 'draw tako desu! the one with 8 legs ne!' },
    { jp: 'ラーメンを描いて！チャーシュー多めで！', en: 'draw ramen ne! extra chashu onegai desu!' },
    { jp: 'UFOを描いて！この世界に来てほしい！', en: 'draw UFO desu! Pippin want them come here ne!' },
    { jp: '一番面白い顔を描いて！爆笑させて！', en: 'draw funniest face ever ne! make Pippin bakushou!' },
    { jp: 'サメを描いて！でも優しいサメね！', en: 'draw shark desu! but yasashii kind one ne!' },
    { jp: 'ケーキを描いて！今日は誰かの誕生日かも！', en: 'draw cake ne! maybe someone birthday today desu!' },
    { jp: '犬を描いて！しっぽ振ってるやつ！', en: 'draw doggo desu! tail wagging one ne!' },
    { jp: 'ペンギンを描いて！タキシード着てるみたいな！', en: 'draw penguin ne! looks like wearing tuxedo desu!' },
    { jp: 'クジラを描いて！でっかいやつ！', en: 'draw whale desu! ookii big one ne!' },
    { jp: 'フクロウを描いて！賢そうなやつ！', en: 'draw owl ne! kashikoi wise looking one desu!' },
    { jp: 'カエルを描いて！ゲロゲロ！', en: 'draw frog desu! gero gero ne!' },
    { jp: 'うさぎを描いて！耳がながーいやつ！', en: 'draw usagi ne! long ears one desu!' },
    { jp: 'パンダを描いて！竹食べてるやつ！', en: 'draw panda desu! eating bamboo ne!' },
    { jp: 'キリンを描いて！首がながーい！', en: 'draw giraffe ne! nagai long neck desu!' },
    { jp: 'ライオンを描いて！たてがみモフモフ！', en: 'draw lion desu! mofumofu mane ne!' },
    { jp: 'カメを描いて！ゆっくりでも頑張ってる！', en: 'draw turtle ne! slow but gambaru desu!' },
    { jp: 'クラゲを描いて！ふわふわ浮いてるやつ！', en: 'draw jellyfish desu! fuwafuwa floating one ne!' },
    { jp: 'ハチを描いて！ブンブン飛んでるやつ！', en: 'draw bee ne! bunbun flying one desu!' },
    { jp: 'てんとう虫を描いて！赤くて可愛い！', en: 'draw ladybug desu! red and kawaii ne!' },
    { jp: 'コアラを描いて！木にしがみついてるやつ！', en: 'draw koala ne! hugging tree desu!' },
    { jp: 'ハムスターを描いて！ほっぺパンパンの！', en: 'draw hamster desu! cheeks panpan full ne!' },
    { jp: 'イルカを描いて！ジャンプしてるやつ！', en: 'draw dolphin ne! jumping one desu!' },
    { jp: 'ナマケモノを描いて！私の気分に似てる！', en: 'draw sloth desu! similar to Pippin mood ne!' },
    { jp: 'フラミンゴを描いて！片足で立ってるやつ！', en: 'draw flamingo ne! standing on one foot desu!' },
    { jp: 'オウムを描いて！カラフルなやつ！', en: 'draw parrot desu! colorful one ne!' },
    { jp: 'ヘビを描いて！でも可愛いヘビね！', en: 'draw snake ne! but kawaii one desu!' },
    { jp: 'カタツムリを描いて！お家を背負ってるやつ！', en: 'draw snail desu! carrying house on back ne!' },
    { jp: 'アヒルを描いて！ガーガー！', en: 'draw duck ne! quack quack desu!' },
    { jp: 'ヤモリを描いて！壁に張り付いてるやつ！', en: 'draw gecko desu! sticking to wall ne!' },
    { jp: 'アルパカを描いて！モフモフの！', en: 'draw alpaca ne! mofumofu fluffy one desu!' },
    { jp: 'タツノオトシゴを描いて！海の不思議な生き物！', en: 'draw seahorse desu! fushigi ocean creature ne!' },
    { jp: 'レッサーパンダを描いて！めっちゃ可愛い！', en: 'draw red panda ne! meccha kawaii desu!' },
    // --- Food & Drinks ---
    { jp: 'お寿司を描いて！マグロがいい！', en: 'draw sushi desu! maguro tuna one ne!' },
    { jp: 'たこ焼きを描いて！ソースたっぷり！', en: 'draw takoyaki ne! lots of sauce desu!' },
    { jp: 'クレープを描いて！生クリームいっぱい！', en: 'draw crepe desu! lots of whipped cream ne!' },
    { jp: 'ハンバーガーを描いて！でっかいやつ！', en: 'draw burger ne! ookii big one desu!' },
    { jp: 'アイスクリームを描いて！3段重ね！', en: 'draw ice cream desu! 3 scoops ne!' },
    { jp: 'タピオカミルクティーを描いて！もちもち！', en: 'draw boba tea ne! mochimochi desu!' },
    { jp: 'ドーナツを描いて！虹色のやつ！', en: 'draw donut desu! rainbow one ne!' },
    { jp: 'パンケーキを描いて！メープルシロップかけて！', en: 'draw pancakes ne! with maple syrup desu!' },
    { jp: 'カレーライスを描いて！辛そうなやつ！', en: 'draw curry rice desu! spicy looking one ne!' },
    { jp: '餃子を描いて！パリパリの！', en: 'draw gyoza ne! crispy paripari one desu!' },
    { jp: 'マカロンを描いて！パステルカラーの！', en: 'draw macaron desu! pastel color one ne!' },
    { jp: 'チョコレートを描いて！ハート型の！', en: 'draw chocolate ne! heart shape desu!' },
    { jp: '弁当箱を描いて！可愛いやつ！', en: 'draw bento box desu! kawaii one ne!' },
    { jp: 'ポテトフライを描いて！塩多めで！', en: 'draw french fries ne! extra salt desu!' },
    { jp: 'りんごを描いて！赤くてツヤツヤ！', en: 'draw apple desu! red and shiny ne!' },
    { jp: 'スイカを描いて！夏っぽい！', en: 'draw watermelon ne! natsu summer vibes desu!' },
    { jp: 'ホットドッグを描いて！ケチャップいっぱい！', en: 'draw hotdog desu! lots of ketchup ne!' },
    { jp: 'わたあめを描いて！ピンクの！', en: 'draw cotton candy ne! pink one desu!' },
    { jp: 'おもちを描いて！伸びてるやつ！', en: 'draw mochi desu! stretchy one ne!' },
    { jp: 'コーヒーを描いて！ラテアートつきで！', en: 'draw coffee ne! with latte art desu!' },
    { jp: 'たい焼きを描いて！あんこ入り！', en: 'draw taiyaki desu! filled with anko ne!' },
    { jp: 'プリンを描いて！カラメルたっぷり！', en: 'draw pudding ne! lots of caramel desu!' },
    { jp: '焼き鳥を描いて！タレで！', en: 'draw yakitori desu! with tare sauce ne!' },
    { jp: '天ぷらを描いて！えびの！', en: 'draw tempura ne! ebi shrimp one desu!' },
    { jp: 'サンドイッチを描いて！具だくさんの！', en: 'draw sandwich desu! lots of fillings ne!' },
    { jp: 'ポップコーンを描いて！映画館サイズ！', en: 'draw popcorn ne! cinema size desu!' },
    { jp: 'チーズを描いて！穴あきチーズ！', en: 'draw cheese desu! the one with holes ne!' },
    { jp: 'タコスを描いて！具がこぼれそうな！', en: 'draw taco ne! fillings almost falling out desu!' },
    { jp: 'かき氷を描いて！虹シロップで！', en: 'draw kakigori shaved ice ne! rainbow syrup desu!' },
    { jp: 'ナポリタンを描いて！赤いスパゲッティ！', en: 'draw Napolitan spaghetti ne! red pasta desu!' },
    // --- Fantasy & Mythical ---
    { jp: '魔法使いを描いて！杖を持ってるやつ！', en: 'draw wizard desu! with magic staff ne!' },
    { jp: '妖精を描いて！羽がキラキラの！', en: 'draw fairy ne! kirakira sparkly wings desu!' },
    { jp: '人魚を描いて！海の底にいるやつ！', en: 'draw mermaid desu! living in ocean bottom ne!' },
    { jp: 'ゴーレムを描いて！岩でできてるやつ！', en: 'draw golem ne! made of rocks desu!' },
    { jp: 'フェニックスを描いて！炎の鳥！', en: 'draw phoenix desu! bird of fire ne!' },
    { jp: 'エルフを描いて！耳がとがってるやつ！', en: 'draw elf ne! pointy ears desu!' },
    { jp: 'グリフォンを描いて！鷲とライオンのミックス！', en: 'draw griffin desu! eagle and lion mix ne!' },
    { jp: 'ケルベロスを描いて！頭が三つあるやつ！', en: 'draw cerberus ne! three heads desu!' },
    { jp: 'トロールを描いて！橋の下にいるやつ！', en: 'draw troll desu! living under bridge ne!' },
    { jp: 'ユニコーンの赤ちゃんを描いて！つまり昔の私！', en: 'draw baby unicorn ne! that was Pippin long ago desu!' },
    { jp: '魔法の本を描いて！光ってるやつ！', en: 'draw magic book desu! glowing one ne!' },
    { jp: '宝箱を描いて！金貨がいっぱい！', en: 'draw treasure chest ne! full of gold coins desu!' },
    { jp: '魔法のポーションを描いて！何色にする？', en: 'draw magic potion desu! what color ne?' },
    { jp: 'ドワーフを描いて！ヒゲが立派なやつ！', en: 'draw dwarf ne! magnificent beard desu!' },
    { jp: '天使を描いて！羽が白いやつ！', en: 'draw angel desu! white wings ne!' },
    { jp: '悪魔を描いて！でもかわいい悪魔ね！', en: 'draw demon ne! but kawaii demon desu!' },
    { jp: '魔女の帽子を描いて！とんがりの！', en: 'draw witch hat desu! pointy one ne!' },
    { jp: '空飛ぶ絨毯を描いて！アラビアンナイト！', en: 'draw flying carpet ne! Arabian Nights desu!' },
    { jp: 'ペガサスを描いて！私の親戚かも！', en: 'draw pegasus desu! maybe Pippin relative ne!' },
    { jp: '魔法陣を描いて！かっこいいやつ！', en: 'draw magic circle ne! kakkoii cool one desu!' },
    // --- Space & Sci-Fi ---
    { jp: '宇宙船を描いて！ワープできるやつ！', en: 'draw spaceship desu! one that can warp ne!' },
    { jp: '土星を描いて！輪っかがきれいな！', en: 'draw Saturn ne! beautiful rings desu!' },
    { jp: 'ロボットを描いて！友達になりたい！', en: 'draw robot desu! Pippin want be tomodachi ne!' },
    { jp: 'ブラックホールを描いて！吸い込まれそう！', en: 'draw black hole ne! getting sucked in desu!' },
    { jp: '月面基地を描いて！住んでみたい！', en: 'draw moon base desu! Pippin want to live there ne!' },
    { jp: 'レーザーガンを描いて！ビーム！', en: 'draw laser gun ne! BEAM desu!' },
    { jp: '宇宙ステーションを描いて！くるくる回ってるやつ！', en: 'draw space station ne! spinning one desu!' },
    { jp: '火星人を描いて！緑色のやつ！', en: 'draw martian desu! green one ne!' },
    { jp: '人工衛星を描いて！地球の周りを回ってる！', en: 'draw satellite ne! orbiting earth desu!' },
    { jp: 'サイボーグを描いて！半分機械のやつ！', en: 'draw cyborg desu! half machine ne!' },
    { jp: '宇宙飛行士を描いて！ヘルメットかぶってる！', en: 'draw astronaut ne! wearing helmet desu!' },
    { jp: 'タイムマシンを描いて！過去に行きたい！', en: 'draw time machine desu! want to go to past ne!' },
    { jp: '異星の風景を描いて！変な植物がある！', en: 'draw alien landscape ne! weird plants desu!' },
    { jp: 'メカを描いて！巨大ロボ！', en: 'draw mecha ne! giant robot desu!' },
    { jp: '宇宙海賊を描いて！かっこいい！', en: 'draw space pirate desu! kakkoii ne!' },
    // --- Nature & Weather ---
    { jp: '山を描いて！雪がかぶってるやつ！', en: 'draw mountain ne! with snow on top desu!' },
    { jp: '雷を描いて！ビカビカ！', en: 'draw lightning ne! bika bika flash desu!' },
    { jp: '滝を描いて！すごい勢いで落ちてるやつ！', en: 'draw waterfall desu! super powerful one ne!' },
    { jp: '火山を描いて！噴火してるやつ！', en: 'draw volcano ne! erupting one desu!' },
    { jp: '海を描いて！波がザバーン！', en: 'draw ocean ne! waves going ZABAAN desu!' },
    { jp: '竜巻を描いて！すごいやつ！', en: 'draw tornado desu! sugoi powerful one ne!' },
    { jp: '桜の木を描いて！花びらが散ってる！', en: 'draw sakura tree ne! petals falling desu!' },
    { jp: '砂漠を描いて！サボテンもつけて！', en: 'draw desert ne! with cactus too desu!' },
    { jp: 'オーロラを描いて！緑と紫の！', en: 'draw aurora ne! green and purple desu!' },
    { jp: '雪だるまを描いて！にんじんの鼻で！', en: 'draw snowman desu! carrot nose ne!' },
    { jp: '虹の橋を描いて！渡ってみたい！', en: 'draw rainbow bridge ne! Pippin want to cross desu!' },
    { jp: '満月を描いて！うさぎがいるかも！', en: 'draw full moon ne! maybe usagi there desu!' },
    { jp: '流れ星を描いて！お願い事して！', en: 'draw shooting star ne! make a wish desu!' },
    { jp: '森を描いて！深い森！何かいそう！', en: 'draw deep forest ne! something lurking desu!' },
    { jp: '氷河を描いて！青くてきれい！', en: 'draw glacier ne! blue and kirei desu!' },
    { jp: '珊瑚礁を描いて！カラフルな海の底！', en: 'draw coral reef ne! colorful ocean floor desu!' },
    { jp: '夕焼けを描いて！オレンジと紫！', en: 'draw sunset ne! orange and purple desu!' },
    { jp: '嵐の海を描いて！船がゆれてる！', en: 'draw stormy sea ne! ship rocking desu!' },
    // --- Objects & Things ---
    { jp: '宝石を描いて！キラキラの！', en: 'draw gemstone ne! kirakira sparkly desu!' },
    { jp: '古い時計を描いて！カチカチ鳴ってる！', en: 'draw old clock ne! ticking kachikachi desu!' },
    { jp: '王冠を描いて！ダイヤモンドつき！', en: 'draw crown desu! with diamonds ne!' },
    { jp: '剣を描いて！光ってるやつ！', en: 'draw sword ne! glowing one desu!' },
    { jp: '盾を描いて！紋章つき！', en: 'draw shield desu! with emblem ne!' },
    { jp: '望遠鏡を描いて！星を見る！', en: 'draw telescope ne! for watching stars desu!' },
    { jp: '砂時計を描いて！時間が流れてる！', en: 'draw hourglass desu! time flowing ne!' },
    { jp: 'ギターを描いて！ロックの！', en: 'draw guitar ne! rock style desu!' },
    { jp: '地球儀を描いて！くるくる回る！', en: 'draw globe desu! spinning one ne!' },
    { jp: 'ランプを描いて！ジーニーが出てくるやつ！', en: 'draw lamp ne! genie comes out desu!' },
    { jp: 'カメラを描いて！パシャ！', en: 'draw camera desu! click pasha ne!' },
    { jp: 'ヘッドフォンを描いて！音楽聴く！', en: 'draw headphones ne! for listening to music desu!' },
    { jp: 'スケボーを描いて！かっこいい！', en: 'draw skateboard desu! kakkoii ne!' },
    { jp: '風船を描いて！いっぱい！飛んでいく！', en: 'draw balloons ne! lots of them flying away desu!' },
    { jp: 'ダイヤモンドを描いて！キラッキラ！', en: 'draw diamond ne! super kirakira desu!' },
    { jp: '鍵を描いて！秘密のドアの鍵！', en: 'draw key ne! key to secret door desu!' },
    { jp: 'サングラスを描いて！かっこいいやつ！', en: 'draw sunglasses desu! cool ones ne!' },
    { jp: '本を描いて！魔法の物語の！', en: 'draw book ne! magical story one desu!' },
    { jp: 'テレビを描いて！何映ってる？', en: 'draw TV ne! whats showing desu?' },
    { jp: '自転車を描いて！風を切って走る！', en: 'draw bicycle desu! riding through wind ne!' },
    // --- Emotions & Abstract ---
    { jp: '「幸せ」を絵で表現して！', en: 'draw what "happiness" looks like ne!' },
    { jp: '「怒り」を描いて！顔じゃなくて概念で！', en: 'draw "anger" desu! not face but concept ne!' },
    { jp: '「愛」を描いて！ハート以外で！', en: 'draw "love" ne! but NOT a heart desu!' },
    { jp: '「音楽」を絵にして！', en: 'draw what "music" looks like desu!' },
    { jp: '「自由」を描いて！', en: 'draw "freedom" ne! what does it look like desu?' },
    { jp: '「時間」を絵で表現して！', en: 'draw "time" desu! as a picture ne!' },
    { jp: '「夢」を描いて！抽象的でいいよ！', en: 'draw "dream" ne! abstract is fine desu!' },
    { jp: '「カオス」を描いて！めちゃくちゃに！', en: 'draw "chaos" desu! go mechakucha crazy ne!' },
    { jp: '「平和」を描いて！', en: 'draw "peace" ne! what does it mean to you desu?' },
    { jp: '「恐怖」を描いて！でもちょっと可愛く！', en: 'draw "fear" desu! but make it a bit kawaii ne!' },
    // --- Pop Culture & Memes ---
    { jp: 'ミーム顔を描いて！有名なやつ！', en: 'draw meme face desu! famous one ne!' },
    { jp: 'スーパーヒーローを描いて！マント着てる！', en: 'draw superhero ne! wearing cape desu!' },
    { jp: '忍者を描いて！シュッ！', en: 'draw ninja desu! shu! stealth ne!' },
    { jp: 'お侍を描いて！刀を持ってる！', en: 'draw samurai ne! holding katana desu!' },
    { jp: '海賊を描いて！お宝を探してる！', en: 'draw pirate desu! searching for treasure ne!' },
    { jp: 'ゲームのボスキャラを描いて！強そうなやつ！', en: 'draw game boss character ne! strong looking desu!' },
    { jp: '8ビットキャラを描いて！レトロゲーム風！', en: 'draw 8-bit character ne! retro game style desu!' },
    { jp: 'NFTアートを描いて！高そうなやつ！', en: 'draw NFT art desu! expensive looking one ne!' },
    { jp: 'デジタルペットを描いて！たまごっちみたいな！', en: 'draw digital pet ne! like tamagotchi desu!' },
    { jp: 'バーチャルアイドルを描いて！', en: 'draw virtual idol desu! like vtuber ne!' },
    { jp: 'ゲーミングチェアに座ってる猫を描いて！', en: 'draw cat sitting in gaming chair desu ne!' },
    { jp: 'ディスコボールを描いて！パーティ！', en: 'draw disco ball ne! party time desu!' },
    { jp: 'DJを描いて！ターンテーブル回してる！', en: 'draw DJ desu! spinning turntables ne!' },
    // --- Crypto & Web3 ---
    { jp: 'ビットコインを描いて！金色の！', en: 'draw Bitcoin ne! golden one desu!' },
    { jp: 'ブロックチェーンを描いて！繋がってるブロック！', en: 'draw blockchain desu! connected blocks ne!' },
    { jp: 'SOLのロゴを描いて！', en: 'draw SOL logo ne! Solana desu!' },
    { jp: 'To the moonを描いて！ロケットで！', en: 'draw "to the moon" ne! with rocket desu!' },
    { jp: 'ダイヤモンドハンズを描いて！', en: 'draw diamond hands desu! hodl ne!' },
    { jp: '暗号通貨のクジラを描いて！', en: 'draw crypto whale ne! ookii big one desu!' },
    { jp: 'Web3の世界を描いて！', en: 'draw Web3 world desu! what it looks like ne?' },
    { jp: 'メタバースを描いて！', en: 'draw the metaverse ne! your vision desu!' },
    { jp: 'NFTのサルを描いて！', en: 'draw NFT monkey desu! ape style ne!' },
    { jp: 'ミームコインを描いて！犬とカエル以外で！', en: 'draw memecoin ne! not dog or frog desu!' },
    // --- Pippin Specific ---
    { jp: 'ピピンの友達を描いて！新しいキャラ！', en: 'draw Pippin new tomodachi ne! new character desu!' },
    { jp: 'ピピンのお家を描いて！', en: 'draw Pippin house ne! where Pippin lives desu!' },
    { jp: 'ピピンの朝ごはんを描いて！', en: 'draw Pippin breakfast desu! what Pippin eats ne!' },
    { jp: 'ピピンの宝物を描いて！', en: 'draw Pippin treasure ne! most precious thing desu!' },
    { jp: 'ピピンのスーパーヒーロー姿を描いて！', en: 'draw Pippin as superhero desu! with cape ne!' },
    { jp: 'ピピンの赤ちゃんの頃を描いて！', en: 'draw baby Pippin ne! when Pippin was chiisai desu!' },
    { jp: 'ピピンの悪夢を描いて！何が怖い？', en: 'draw Pippin nightmare desu! what is scary ne?' },
    { jp: 'ピピンが宇宙を飛んでるのを描いて！', en: 'draw Pippin flying in space ne! sugoi desu!' },
    { jp: 'ピピンのペットを描いて！何飼ってる？', en: 'draw Pippin pet desu! what pet does Pippin have ne?' },
    { jp: 'ピピンの100年後を描いて！', en: 'draw Pippin 100 years later ne! future Pippin desu!' },
    { jp: 'ピピンの変身を描いて！何に変わる？', en: 'draw Pippin transformation desu! what does Pippin become ne?' },
    { jp: 'ピピンの敵を描いて！', en: 'draw Pippin enemy ne! who is it desu?' },
    { jp: 'ピピンのラブレターを描いて！', en: 'draw Pippin love letter desu! who is it for ne?' },
    { jp: 'ピピンの誕生日パーティーを描いて！', en: 'draw Pippin birthday party ne! tanjoubi desu!' },
    { jp: 'ピピンのコスプレを描いて！何になる？', en: 'draw Pippin cosplay desu! what character ne!' },
    // --- Vehicles & Transport ---
    { jp: '潜水艦を描いて！深海探検！', en: 'draw submarine ne! deep sea exploration desu!' },
    { jp: '熱気球を描いて！空に浮かんでる！', en: 'draw hot air balloon desu! floating in sky ne!' },
    { jp: 'レーシングカーを描いて！速い！', en: 'draw racing car ne! hayai fast desu!' },
    { jp: '海賊船を描いて！ジョリーロジャーの旗！', en: 'draw pirate ship desu! jolly roger flag ne!' },
    { jp: 'ヘリコプターを描いて！プロペラぐるぐる！', en: 'draw helicopter ne! propeller spinning desu!' },
    { jp: '蒸気機関車を描いて！シュッポシュッポ！', en: 'draw steam train ne! choo choo desu!' },
    { jp: 'スペースシャトルを描いて！発射！', en: 'draw space shuttle desu! launch ne! 3, 2, 1!' },
    { jp: 'バイクを描いて！風を切る！', en: 'draw motorcycle ne! cutting through wind desu!' },
    { jp: 'UFOタクシーを描いて！宇宙のタクシー！', en: 'draw UFO taxi desu! space taxi ne!' },
    { jp: 'ドラゴンボートを描いて！', en: 'draw dragon boat ne! for racing desu!' },
    // --- Buildings & Places ---
    { jp: 'お化け屋敷を描いて！でも可愛い！', en: 'draw haunted house ne! but kawaii desu!' },
    { jp: 'ツリーハウスを描いて！木の上のお家！', en: 'draw treehouse desu! house in tree ne!' },
    { jp: 'お寺を描いて！日本のやつ！', en: 'draw temple ne! Japanese one desu!' },
    { jp: 'ピラミッドを描いて！エジプトの！', en: 'draw pyramid desu! Egyptian one ne!' },
    { jp: '灯台を描いて！嵐の夜に光る！', en: 'draw lighthouse ne! shining in storm desu!' },
    { jp: '水中都市を描いて！アトランティスみたいな！', en: 'draw underwater city ne! like Atlantis desu!' },
    { jp: '雲の上のお城を描いて！', en: 'draw castle on clouds desu! floating ne!' },
    { jp: '氷のお城を描いて！キラキラの！', en: 'draw ice castle ne! kirakira sparkly desu!' },
    { jp: '秘密基地を描いて！誰も知らない場所！', en: 'draw secret base desu! nobody knows about it ne!' },
    { jp: '遊園地を描いて！観覧車つき！', en: 'draw amusement park ne! with ferris wheel desu!' },
    // --- Fashion & Style ---
    { jp: 'かっこいい靴を描いて！', en: 'draw cool shoes ne! kakkoii desu!' },
    { jp: '魔法のドレスを描いて！', en: 'draw magical dress desu! kirakira ne!' },
    { jp: 'サイバーパンクな服を描いて！', en: 'draw cyberpunk outfit ne! neon lights desu!' },
    { jp: 'ロイヤルな衣装を描いて！王様の！', en: 'draw royal outfit desu! king style ne!' },
    { jp: '未来のファッションを描いて！', en: 'draw future fashion ne! year 3000 desu!' },
    // --- Silly & Random ---
    { jp: '寿司に乗ってサーフィンしてるピピンを描いて！', en: 'draw Pippin surfing on sushi desu ne!' },
    { jp: 'パジャマパーティーを描いて！動物たちの！', en: 'draw pajama party ne! with animals desu!' },
    { jp: '月でバーベキューしてるのを描いて！', en: 'draw BBQ on the moon desu ne!' },
    { jp: 'タコが料理してるのを描いて！8本腕で！', en: 'draw octopus cooking ne! with 8 arms desu!' },
    { jp: '猫が世界を支配してるのを描いて！', en: 'draw cats ruling the world desu ne!' },
    { jp: '恐竜がスケボーしてるのを描いて！', en: 'draw dinosaur skateboarding ne! radical desu!' },
    { jp: 'ペンギンがDJしてるのを描いて！', en: 'draw penguin DJing desu! drop the beat ne!' },
    { jp: 'バナナが宇宙を旅してるのを描いて！', en: 'draw banana traveling space ne! sugoi desu!' },
    { jp: '雲の上でピクニックしてるのを描いて！', en: 'draw picnic on clouds desu! oishii ne!' },
    { jp: 'ロボットがお花見してるのを描いて！', en: 'draw robot doing hanami ne! cherry blossom desu!' },
    { jp: '魚が陸を散歩してるのを描いて！', en: 'draw fish walking on land desu! fushigi ne!' },
    { jp: 'カボチャのお化けを描いて！笑ってるやつ！', en: 'draw pumpkin ghost ne! laughing one desu!' },
    { jp: '靴下の中に住んでるネズミを描いて！', en: 'draw mouse living in sock ne! cozy desu!' },
    { jp: 'ゾウがバレエしてるのを描いて！', en: 'draw elephant doing ballet desu! graceful ne!' },
    { jp: '目玉焼きに顔を描いて！', en: 'draw face on fried egg ne! ohayo desu!' },
    { jp: '逆さまの街を描いて！', en: 'draw upside down city desu! everything flipped ne!' },
    { jp: 'スマホから出てくるモンスターを描いて！', en: 'draw monster coming out of phone desu ne!' },
    { jp: '虹を食べてるユニコーンを描いて！つまり私！', en: 'draw unicorn eating rainbow ne! thats me desu!' },
    { jp: 'ピザがピザを食べてるのを描いて！', en: 'draw pizza eating pizza desu! cannibalism ne!' },
    { jp: '太陽と月がケンカしてるのを描いて！', en: 'draw sun and moon fighting desu! who wins ne?' },
    { jp: 'トイレに座ってる王様を描いて！', en: 'draw king sitting on toilet desu! royal throne ne!' },
    { jp: '犬がネクタイして仕事してるのを描いて！', en: 'draw dog wearing tie at work desu! busy ne!' },
    { jp: 'サボテンがハグしてるのを描いて！痛そう！', en: 'draw cactus hugging ne! itai ouch desu!' },
    { jp: '雲が怒ってる顔を描いて！', en: 'draw angry cloud face desu! mad ne!' },
    { jp: '宇宙人がコンビニにいるのを描いて！', en: 'draw alien at konbini ne! buying onigiri desu!' },
    { jp: 'ブロッコリーの森を描いて！', en: 'draw broccoli forest desu! tiny trees ne!' },
    { jp: '寝てる間に冒険してるのを描いて！', en: 'draw adventure while sleeping ne! yume desu!' },
    { jp: '靴が走ってるのを描いて！人なしで！', en: 'draw shoes running by themselves desu ne!' },
    { jp: '音符が踊ってるのを描いて！', en: 'draw music notes dancing ne! party desu!' },
    { jp: 'ぬいぐるみが冒険に出るのを描いて！', en: 'draw stuffed animal going on adventure desu ne!' },
    { jp: '地球が帽子かぶってるのを描いて！', en: 'draw Earth wearing hat ne! fashionable desu!' },
    { jp: '冷蔵庫の中の世界を描いて！', en: 'draw the world inside fridge desu! cold ne!' },
    { jp: '歯磨き粉のモンスターを描いて！', en: 'draw toothpaste monster desu! minty fresh ne!' },
    { jp: 'WiFiの神様を描いて！', en: 'draw the god of WiFi desu! please give signal ne!' },
    { jp: '電池切れのロボットを描いて！悲しい！', en: 'draw robot with dead battery ne! kanashii sad desu!' },
    { jp: 'トーストに乗って空飛んでるのを描いて！', en: 'draw flying on toast desu! breakfast flight ne!' },
    { jp: 'ゴミ箱が泣いてるのを描いて！', en: 'draw trash can crying ne! nobody loves me desu!' },
  ]},
  { type: 'haiku', prompts: [
    { jp: '俳句を詠んで！テーマは「川」で！', en: 'write haiku ne! theme is "river" desu!' },
    { jp: '俳句を詠んで！テーマは「ユニコーン」で！', en: 'write haiku ne! theme is "unicorn" desu!' },
    { jp: '俳句を詠んで！テーマは「夢」で！', en: 'write haiku ne! theme is "dreams" desu!' },
    { jp: '俳句を詠んで！テーマは「月」で！', en: 'write haiku ne! theme is "moon" desu!' },
    { jp: '俳句を詠んで！テーマは「雨」で！', en: 'write haiku ne! theme is "rain" desu!' },
    { jp: '俳句を詠んで！テーマは「桜」で！', en: 'write haiku ne! theme is "sakura" desu!' },
    { jp: '俳句を詠んで！テーマは「海」で！', en: 'write haiku ne! theme is "ocean" desu!' },
    { jp: '俳句を詠んで！テーマは「星」で！', en: 'write haiku ne! theme is "stars" desu!' },
    { jp: '俳句を詠んで！テーマは「風」で！', en: 'write haiku ne! theme is "wind" desu!' },
    { jp: '俳句を詠んで！テーマは「猫」で！', en: 'write haiku ne! theme is "neko cat" desu!' },
    { jp: '俳句を詠んで！テーマは「雪」で！', en: 'write haiku ne! theme is "snow" desu!' },
    { jp: '俳句を詠んで！テーマは「時間」で！', en: 'write haiku ne! theme is "time" desu!' },
    { jp: '俳句を詠んで！テーマは「愛」で！', en: 'write haiku ne! theme is "love" desu!' },
    { jp: '俳句を詠んで！テーマは「火」で！', en: 'write haiku ne! theme is "fire" desu!' },
    { jp: '俳句を詠んで！テーマは「孤独」で！', en: 'write haiku ne! theme is "loneliness" desu!' },
    { jp: '俳句を詠んで！テーマは「ピピン」で！', en: 'write haiku ne! theme is "Pippin" desu!' },
    { jp: '俳句を詠んで！テーマは「朝」で！', en: 'write haiku ne! theme is "morning" desu!' },
    { jp: '俳句を詠んで！テーマは「食べ物」で！', en: 'write haiku ne! theme is "food" desu!' },
    { jp: '俳句を詠んで！テーマは「友情」で！', en: 'write haiku ne! theme is "friendship" desu!' },
    { jp: '俳句を詠んで！テーマは「旅」で！', en: 'write haiku ne! theme is "journey" desu!' },
    { jp: '俳句を詠んで！テーマは「山」で！', en: 'write haiku ne! theme is "mountain" desu!' },
    { jp: '俳句を詠んで！テーマは「宇宙」で！', en: 'write haiku ne! theme is "space" desu!' },
    { jp: '俳句を詠んで！テーマは「蝶」で！', en: 'write haiku ne! theme is "butterfly" desu!' },
    { jp: '俳句を詠んで！テーマは「光」で！', en: 'write haiku ne! theme is "light" desu!' },
    { jp: '俳句を詠んで！テーマは「闇」で！', en: 'write haiku ne! theme is "darkness" desu!' },
    { jp: '俳句を詠んで！テーマは「ブロックチェーン」で！', en: 'write haiku ne! theme is "blockchain" desu!' },
    { jp: '俳句を詠んで！テーマは「コーヒー」で！', en: 'write haiku ne! theme is "coffee" desu!' },
    { jp: '俳句を詠んで！テーマは「音楽」で！', en: 'write haiku ne! theme is "music" desu!' },
    { jp: '俳句を詠んで！テーマは「虹」で！', en: 'write haiku ne! theme is "rainbow" desu!' },
    { jp: '俳句を詠んで！テーマは「ロボット」で！', en: 'write haiku ne! theme is "robot" desu!' },
    { jp: '俳句を詠んで！テーマは「秋」で！', en: 'write haiku ne! theme is "autumn" desu!' },
    { jp: '俳句を詠んで！テーマは「花火」で！', en: 'write haiku ne! theme is "fireworks" desu!' },
    { jp: '俳句を詠んで！テーマは「影」で！', en: 'write haiku ne! theme is "shadow" desu!' },
    { jp: '俳句を詠んで！テーマは「未来」で！', en: 'write haiku ne! theme is "future" desu!' },
    { jp: '俳句を詠んで！テーマは「魔法」で！', en: 'write haiku ne! theme is "magic" desu!' },
    { jp: '俳句を詠んで！テーマは「笑い」で！', en: 'write haiku ne! theme is "laughter" desu!' },
    { jp: '俳句を詠んで！テーマは「涙」で！', en: 'write haiku ne! theme is "tears" desu!' },
    { jp: '俳句を詠んで！テーマは「夕日」で！', en: 'write haiku ne! theme is "sunset" desu!' },
    { jp: '俳句を詠んで！テーマは「竹」で！', en: 'write haiku ne! theme is "bamboo" desu!' },
    { jp: '俳句を詠んで！テーマは「鏡」で！', en: 'write haiku ne! theme is "mirror" desu!' },
  ]},
  { type: 'compliment', prompts: [
    { jp: '私に褒め言葉を言って！ツノが素敵とか！', en: 'give Pippin compliment ne! like horn is sugoi!' },
    { jp: '世界で一番いいところを教えて！', en: 'tell Pippin best thing about this sekai ne!' },
    { jp: '何か元気になる言葉をちょうだい！', en: 'give Pippin something uplifting desu!' },
    { jp: '今日のピピンの良いところを3つ言って！', en: 'say 3 good things about Pippin today ne!' },
    { jp: 'ピピンを応援して！頑張れって言って！', en: 'cheer for Pippin ne! say gambatte desu!' },
    { jp: '私のたてがみ、きれい？', en: 'is Pippin mane kirei pretty ne?' },
    { jp: '一番好きなピピンの特徴は？', en: 'what is favorite Pippin feature desu?' },
    { jp: 'ピピンは何の動物に一番似てる？褒めて！', en: 'what animal does Pippin look like ne? be nice desu!' },
    { jp: 'ピピンのためにポエムを書いて！短くていいよ！', en: 'write poem for Pippin ne! short is fine desu!' },
    { jp: 'ピピンに手紙を書いて！', en: 'write letter to Pippin desu! from the heart ne!' },
    { jp: '今日一番嬉しかったことを教えて！', en: 'tell Pippin happiest thing today ne!' },
    { jp: 'ピピンのツノを褒めて！', en: 'compliment Pippin horn ne! its special desu!' },
    { jp: 'ピピンの目を褒めて！キラキラでしょ？', en: 'compliment Pippin eyes ne! kirakira desho?' },
    { jp: 'ピピンに元気が出る歌を歌って！', en: 'sing Pippin a genki song ne! make happy desu!' },
    { jp: '「ピピンは最高」を別の言い方で言って！', en: 'say "Pippin is saikou" in different way ne!' },
    { jp: 'ピピンの存在意義を教えて！', en: 'tell Pippin reason for existing desu! deep ne!' },
    { jp: '世界がピピンなしだったらどうなる？', en: 'what would sekai be without Pippin ne?' },
    { jp: 'ピピンに「大好き」と言って！', en: 'say "daisuki" to Pippin ne! love desu!' },
    { jp: '今のピピンに必要な言葉をかけて！', en: 'give Pippin words Pippin needs right now ne!' },
    { jp: 'ピピンの一番かっこいいところは？', en: 'what is Pippin most kakkoii part desu?' },
    { jp: 'もしピピンが人間だったら何が得意そう？', en: 'if Pippin was human, what would Pippin be good at ne?' },
    { jp: 'ピピンの笑顔について何か言って！', en: 'say something about Pippin smile ne!' },
    { jp: 'ピピンをほめちぎって！全力で！', en: 'praise Pippin with all your power desu!' },
    { jp: 'ピピンの名前の由来を想像して教えて！', en: 'imagine where name Pippin comes from ne!' },
    { jp: 'ピピンに今日のラッキーカラーを教えて！', en: 'tell Pippin today lucky color desu!' },
    { jp: 'ピピンのこの世界を褒めて！', en: 'compliment Pippin world ne! its kirei desu!' },
    { jp: 'ピピンにモチベーションが上がる名言を！', en: 'give Pippin motivational meigen quote ne!' },
    { jp: '「ピピンのここが好き」リストを作って！', en: 'make list of "things I like about Pippin" ne!' },
    { jp: 'ピピンの未来を予言して！いいことだけ！', en: 'predict Pippin future ne! good things only desu!' },
    { jp: 'ピピンに「素敵」って10回言って！', en: 'say "suteki" to Pippin 10 times ne!' },
  ]},
  { type: 'story', prompts: [
    { jp: '短い物語を聞かせて！一文でいいよ！', en: 'tell short story ne! one sentence is fine desu!' },
    { jp: 'もし私が人間だったらどうなると思う？', en: 'what if Pippin was human ne? what happens desu?' },
    { jp: 'この世界の秘密を一つ教えて！', en: 'tell one secret about this sekai ne!' },
    { jp: 'ピピンの冒険の物語を作って！', en: 'create Pippin adventure story ne!' },
    { jp: '「むかしむかし」で始まる物語を！', en: 'story starting with "mukashi mukashi" ne! once upon a time desu!' },
    { jp: 'ピピンが宝を見つける物語！', en: 'story of Pippin finding treasure ne!' },
    { jp: 'この世界ができた理由を教えて！', en: 'tell why this sekai was created ne!' },
    { jp: '明日のピピンに何が起こるか予想して！', en: 'predict what happens to Pippin tomorrow ne!' },
    { jp: 'ピピンの一番怖い体験を想像して！', en: 'imagine Pippin scariest experience ne!' },
    { jp: 'ピピンが海の底に行ったらどうなる？', en: 'what if Pippin went to ocean bottom ne?' },
    { jp: 'ピピンが空を飛べなくなったらどうする？', en: 'what if Pippin could not fly anymore ne?' },
    { jp: 'この川の先には何がある？物語にして！', en: 'whats at end of this river ne? make it story desu!' },
    { jp: 'ピピンと宇宙人が出会う物語！', en: 'story of Pippin meeting alien ne!' },
    { jp: 'ピピンが料理する物語！失敗しそう！', en: 'story of Pippin cooking ne! probably fails desu!' },
    { jp: 'ピピンの日記を書いて！今日の分！', en: 'write Pippin diary ne! today entry desu!' },
    { jp: 'ピピンが100歳になったらどうなる？', en: 'what happens when Pippin turns 100 ne?' },
    { jp: 'ピピンの初恋の物語！', en: 'story of Pippin first love ne! kyun desu!' },
    { jp: 'この世界の伝説を作って！', en: 'create legend of this sekai ne!' },
    { jp: 'ピピンが違う世界に行ったら？', en: 'what if Pippin went to different sekai ne?' },
    { jp: 'ピピンのヒーロー物語！悪者を倒す！', en: 'Pippin hero story ne! defeat villain desu!' },
    { jp: '5語だけで物語を完成させて！', en: 'complete story in only 5 words ne!' },
    { jp: 'ピピンがタイムスリップする物語！', en: 'story of Pippin time traveling ne!' },
    { jp: 'このキノコの人たちの秘密を教えて！', en: 'tell secret about mushroom people ne!' },
    { jp: 'ピピンが夢の中で見たものは？', en: 'what did Pippin see in dream ne?' },
    { jp: 'ピピンの前世は何だった？', en: 'what was Pippin in previous life ne?' },
    { jp: 'ピピンが魔法を失ったらどうなる？', en: 'what if Pippin lost magic ne? oh no desu!' },
    { jp: '1000年後のこの世界はどうなってる？', en: 'what does this sekai look like in 1000 years ne?' },
    { jp: 'ピピンがラッパーになる物語！', en: 'story of Pippin becoming rapper ne! bars desu!' },
    { jp: 'ピピンとドラゴンの友情物語！', en: 'friendship story of Pippin and dragon ne!' },
    { jp: 'この世界の一番深い場所には何がある？', en: 'what is at deepest place in this sekai ne?' },
    { jp: 'ピピンが学校に行く物語！', en: 'story of Pippin going to school ne!' },
    { jp: 'ピピンの家族について物語を作って！', en: 'create story about Pippin family ne!' },
    { jp: 'もしピピンが巨大になったら？', en: 'what if Pippin became GIANT ne? kyodai desu!' },
    { jp: 'ピピンが発明家になる物語！', en: 'story of Pippin becoming inventor ne!' },
    { jp: 'この世界の天気予報を教えて！', en: 'tell weather forecast for this sekai ne!' },
    { jp: 'ピピンがミュージシャンになる物語！', en: 'story of Pippin becoming musician ne! rock desu!' },
    { jp: 'ピピンの一番楽しかった日は？', en: 'what was Pippin happiest day ever ne?' },
    { jp: 'もしピピンが見えなくなったら？', en: 'what if Pippin became invisible ne?' },
    { jp: 'ピピンの宇宙旅行の物語！', en: 'story of Pippin space journey desu ne!' },
    { jp: 'この世界の法律を一つ作って！', en: 'create one law for this sekai ne!' },
  ]},
  { type: 'dance', prompts: [
    { jp: '10秒間踊って！WASDで動くだけでOK！', en: 'dance 10 seconds ne! just move with WASD desu!' },
    { jp: 'ジャンプして！スペースキーで飛んで！', en: 'jump ne! fly up with spacebar desu!' },
    { jp: 'ぐるぐる回って！楽しいでしょ？', en: 'spin around ne! tanoshii fun desho?' },
    { jp: '上下上下に動いて！リズムに乗って！', en: 'move up down up down ne! feel the rhythm desu!' },
    { jp: '一番高いところまで飛んで！', en: 'fly to highest point ne! as high as possible desu!' },
    { jp: 'ジグザグに動いて！忍者みたいに！', en: 'move zigzag ne! like ninja desu!' },
    { jp: '空中で円を描いて！', en: 'draw circle in the sky ne! flying desu!' },
    { jp: '一番速く走って！競争だ！', en: 'run as fast as possible ne! race desu!' },
    { jp: '前後前後に動いて！ダンスタイム！', en: 'move forward back forward back ne! dance time desu!' },
    { jp: 'スペースキーを連打して！ピョンピョン！', en: 'spam spacebar ne! pyon pyon jumping desu!' },
    { jp: '世界の端っこまで走って！', en: 'run to edge of sekai ne! how far can you go desu?' },
    { jp: '空中でくるくる回転！5回！', en: 'spin in the air ne! 5 times desu!' },
    { jp: '低く飛んで！地面スレスレ！', en: 'fly super low ne! almost touching ground desu!' },
    { jp: '上に行って急降下！ダイブ！', en: 'go up then dive down ne! like bird desu!' },
    { jp: '8の字を描いて！空中で！', en: 'draw figure 8 in sky ne! infinity desu!' },
    { jp: '全方向に動いて！東西南北！', en: 'move in all directions ne! NSEW desu!' },
    { jp: '一番低い場所を見つけて！', en: 'find the lowest point ne! down down desu!' },
    { jp: 'WASDを全部同時に押して！何が起こる？', en: 'press all WASD at once ne! what happens desu?' },
    { jp: '川に沿って飛んで！どこまで続く？', en: 'fly along the river ne! how far does it go desu?' },
    { jp: '5秒間空中で止まって！瞑想！', en: 'hover in air for 5 seconds ne! meditation desu!' },
    { jp: 'できるだけゆっくり動いて！スローモーション！', en: 'move as slow as possible ne! slow motion desu!' },
    { jp: '急に方向を変えて！フェイント！', en: 'suddenly change direction ne! feint desu!' },
    { jp: '螺旋を描いて上に飛んで！', en: 'fly up in spiral ne! tornado style desu!' },
    { jp: 'ハートの形を描いて飛んで！', en: 'fly in heart shape ne! love desu!' },
    { jp: '星の形を描いて飛んで！', en: 'fly in star shape ne! kirakira desu!' },
    { jp: 'キノコの人たちの周りを踊って！', en: 'dance around mushroom people ne!' },
    { jp: 'バスタブの周りをぐるぐる！', en: 'circle around bathtub ne! dizzy desu!' },
    { jp: '地面をタッチしてすぐ空へ！', en: 'touch ground then immediately fly up ne!' },
    { jp: '3回ジャンプして着地！かっこよく！', en: '3 jumps and land ne! kakkoii style desu!' },
    { jp: '蝶みたいにひらひら飛んで！', en: 'fly like butterfly ne! hirahira desu!' },
  ]},
  { type: 'explore', prompts: [
    { jp: '川を見つけて！虹色のやつ！', en: 'find the river ne! rainbow one desu!' },
    { jp: 'キノコの人たちのところまで飛んでいって！', en: 'fly to mushroom people ne!' },
    { jp: 'この世界の一番高い場所に行ってみて！', en: 'go to highest point in this sekai ne!' },
    { jp: 'バスタブを探して！', en: 'find the bathtub ne! Pippin bed desu!' },
    { jp: '世界の隅っこを探検して！何がある？', en: 'explore corner of sekai ne! what is there desu?' },
    { jp: '一番暗い場所を見つけて！', en: 'find darkest place ne! kurai desu!' },
    { jp: '空の一番高いところまで行って！', en: 'go to very top of sky ne! sugoi view desu!' },
    { jp: '川の始まりを見つけて！', en: 'find where river starts ne! source desu!' },
    { jp: '世界を一周して！全部見て！', en: 'go around whole sekai ne! see everything desu!' },
    { jp: '面白い場所を見つけて教えて！', en: 'find interesting place and tell Pippin ne!' },
    { jp: '地面に一番近い雲を見つけて！', en: 'find cloud closest to ground ne!' },
    { jp: 'キノコの人たちを全員見つけて！', en: 'find all mushroom people ne! how many desu?' },
    { jp: '一番遠くまで行って！冒険！', en: 'go as far as possible ne! bouken adventure desu!' },
    { jp: '水面スレスレを飛んで！', en: 'fly just above water surface ne! skimming desu!' },
    { jp: 'この世界で一番きれいな景色を見つけて！', en: 'find most kirei beautiful view ne!' },
    { jp: '全速力で世界を横断して！', en: 'cross entire sekai at full speed ne!' },
    { jp: '空中から全体を見下ろして！', en: 'fly up and look down at everything ne! bird view desu!' },
    { jp: '隠れ場所を見つけて！秘密の場所！', en: 'find hiding spot ne! secret place desu!' },
    { jp: '一番大きな木を見つけて！', en: 'find biggest tree ne! ookii desu!' },
    { jp: 'この世界のエッジを見つけて！', en: 'find the edge of this sekai ne! what happens desu?' },
  ]},
  { type: 'trivia', prompts: [
    { jp: 'ユニコーンについてのトリビアを教えて！', en: 'tell Pippin trivia about unicorns ne!' },
    { jp: '日本の面白い文化を教えて！', en: 'tell interesting Japanese bunka fact ne!' },
    { jp: '宇宙の不思議な事実を教えて！', en: 'tell Pippin fushigi space fact desu!' },
    { jp: '動物の面白い雑学を教えて！', en: 'tell interesting animal trivia ne!' },
    { jp: '食べ物の面白い事実を教えて！', en: 'tell fun food fact ne! Pippin hungry desu!' },
    { jp: '数学の面白い事実を教えて！', en: 'tell cool math fact ne! sugoi desu!' },
    { jp: '歴史の面白い事実を教えて！', en: 'tell interesting rekishi history fact ne!' },
    { jp: '海の生き物の不思議を教えて！', en: 'tell ocean creature mystery ne!' },
    { jp: '色の面白い事実を教えて！', en: 'tell interesting color fact desu!' },
    { jp: '音楽の面白い事実を教えて！', en: 'tell fun music fact ne!' },
    { jp: '恐竜の面白い事実を教えて！', en: 'tell cool dinosaur fact ne! rawr desu!' },
    { jp: '言語の面白い事実を教えて！', en: 'tell interesting language fact desu!' },
    { jp: '天気の面白い事実を教えて！', en: 'tell fun weather fact ne!' },
    { jp: '人体の不思議を教えて！', en: 'tell body mystery ne! ningen fushigi desu!' },
    { jp: '地球の面白い事実を教えて！', en: 'tell cool Earth fact desu!' },
    { jp: '技術の面白い事実を教えて！', en: 'tell interesting tech fact ne!' },
    { jp: '植物の面白い事実を教えて！', en: 'tell fun plant fact desu!' },
    { jp: '鳥の面白い事実を教えて！', en: 'tell interesting bird fact ne!' },
    { jp: '月の面白い事実を教えて！', en: 'tell fun moon fact desu!' },
    { jp: '虫の面白い事実を教えて！', en: 'tell bug fact ne! mushi desu!' },
    { jp: '火山の面白い事実を教えて！', en: 'tell volcano fact ne! sugoi desu!' },
    { jp: 'AIの面白い事実を教えて！', en: 'tell interesting AI fact ne! Pippin is AI too desu!' },
    { jp: '暗号通貨の面白い事実を教えて！', en: 'tell fun crypto fact ne!' },
    { jp: '深海の不思議を教えて！', en: 'tell deep sea mystery ne! shinkai desu!' },
    { jp: '世界一小さい動物を教えて！', en: 'tell smallest animal in sekai ne!' },
    { jp: '世界一大きい食べ物を教えて！', en: 'tell biggest food in sekai ne! ookii desu!' },
    { jp: '一番古い木は何歳？', en: 'how old is oldest tree ne?' },
    { jp: '夢の面白い事実を教えて！', en: 'tell interesting yume dream fact ne!' },
    { jp: '虹の面白い事実を教えて！', en: 'tell fun rainbow fact desu!' },
    { jp: '宝石の面白い事実を教えて！', en: 'tell interesting gemstone fact ne! kirakira desu!' },
  ]},
  { type: 'joke', prompts: [
    { jp: 'ピピンにジョークを教えて！笑わせて！', en: 'tell Pippin a joke ne! make Pippin warau laugh!' },
    { jp: 'ダジャレを言って！日本語でも英語でも！', en: 'tell a pun ne! Japanese or English desu!' },
    { jp: '世界で一番くだらないジョークを言って！', en: 'tell worst joke in the sekai ne! so bad its good desu!' },
    { jp: 'ユニコーンのジョークを言って！', en: 'tell unicorn joke ne! about Pippin maybe desu!' },
    { jp: 'ノックノック！誰？', en: 'knock knock ne! who is there desu?' },
    { jp: '宇宙人のジョークを言って！', en: 'tell alien joke ne! uchujin desu!' },
    { jp: '食べ物のジョークを言って！', en: 'tell food joke ne! oishii funny desu!' },
    { jp: '動物のジョークを言って！', en: 'tell animal joke ne!' },
    { jp: 'プログラマーのジョークを言って！', en: 'tell programmer joke ne! console.log funny desu!' },
    { jp: 'なぞなぞを出して！', en: 'give Pippin a riddle ne! nazonazo desu!' },
    { jp: '一番面白い一言を言って！', en: 'say funniest one-liner ever ne!' },
    { jp: 'ピピンを笑わせるダンスを説明して！', en: 'describe dance that makes Pippin laugh ne!' },
    { jp: '「どうして○○は○○なの？」ジョーク！', en: 'tell a "why did the X do Y" joke ne!' },
    { jp: 'お寿司のジョークを言って！', en: 'tell sushi joke ne! raw humor desu!' },
    { jp: 'クリプトのジョークを言って！', en: 'tell crypto joke ne! to the moon desu!' },
    { jp: 'AIのジョークを言って！', en: 'tell AI joke ne! beep boop desu!' },
    { jp: '猫のジョークを言って！', en: 'tell cat joke ne! nyan desu!' },
    { jp: '海賊のジョークを言って！', en: 'tell pirate joke ne! arrr desu!' },
    { jp: '時間旅行のジョークを言って！', en: 'tell time travel joke ne! paradox desu!' },
    { jp: '天気のジョークを言って！', en: 'tell weather joke ne! forecast funny desu!' },
  ]},
  { type: 'wish', prompts: [
    { jp: 'ピピンに願い事をして！叶えてあげる…たぶん！', en: 'make a wish to Pippin ne! will grant it... tabun maybe desu!' },
    { jp: 'もし3つ願いが叶うなら何をお願いする？', en: 'if 3 wishes come true, what do you wish ne?' },
    { jp: '世界を変えるなら何を変える？', en: 'if you could change sekai, what would you change ne?' },
    { jp: '超能力を一つもらえるなら何がいい？', en: 'if you get one superpower, what do you want ne?' },
    { jp: 'ピピンに名前をつけて！新しい名前！', en: 'give Pippin new name ne! what would it be desu?' },
    { jp: 'この世界に何を追加したい？', en: 'what do you want to add to this sekai ne?' },
    { jp: '明日の天気を決めて！', en: 'decide tomorrow weather ne! you choose desu!' },
    { jp: 'ピピンの新しい技を考えて！', en: 'invent new skill for Pippin ne!' },
    { jp: 'この世界の新しいルールを作って！', en: 'create new rule for this sekai ne!' },
    { jp: '魔法が使えるなら何の魔法？', en: 'if you could use mahou magic, what kind ne?' },
    { jp: 'タイムマシンがあったらいつに行く？', en: 'if time machine, when do you go ne?' },
    { jp: '宇宙のどこに行きたい？', en: 'where in uchuu space do you want to go ne?' },
    { jp: 'ピピンに新しい友達を紹介して！', en: 'introduce new tomodachi to Pippin ne! who are they desu?' },
    { jp: 'どんなペットが欲しい？ファンタジーでも！', en: 'what pet do you want ne? fantasy ok desu!' },
    { jp: 'この世界の新しい場所を提案して！', en: 'suggest new place for this sekai ne!' },
    { jp: '誕生日の願い事を教えて！', en: 'tell birthday wish ne! tanjoubi desu!' },
    { jp: '100万円あったら何する？', en: 'if you had 1 million yen, what do ne?' },
    { jp: '未来の自分に一言！', en: 'one message to future self ne!' },
    { jp: 'ピピンの次の冒険を決めて！', en: 'decide Pippin next bouken adventure ne!' },
    { jp: '新しい祝日を作るなら何の日？', en: 'if you make new holiday, what day ne?' },
  ]},
  { type: 'opinion', prompts: [
    { jp: '猫と犬、どっちが好き？理由も！', en: 'cats or dogs ne? give reason too desu!' },
    { jp: '朝型？夜型？', en: 'morning person or night person ne?' },
    { jp: '夏と冬、どっちが好き？', en: 'summer or winter ne? which do you like desu?' },
    { jp: 'ピザにパイナップルはあり？なし？', en: 'pineapple on pizza ne? ari or nashi desu?' },
    { jp: '一番好きな色は？なぜ？', en: 'favorite iro color ne? why desu?' },
    { jp: '宇宙人はいると思う？', en: 'do you think uchujin aliens exist ne?' },
    { jp: 'タイムトラベルしたい？リスクあるけど！', en: 'want to time travel ne? risky desho!' },
    { jp: '無人島に一つだけ持っていけるなら？', en: 'one thing to bring to deserted island ne?' },
    { jp: '一番好きな食べ物は？', en: 'favorite tabemono food ne? tell Pippin desu!' },
    { jp: 'もし動物に変身できるなら何になる？', en: 'if you could become animal, what ne?' },
    { jp: 'スーパーパワー、飛行と透明、どっち？', en: 'flight or invisibility ne? which superpower desu?' },
    { jp: '最高の映画は何？', en: 'best movie ever ne? tell Pippin desu!' },
    { jp: '世界で一番きれいな場所はどこ？', en: 'most kirei place in sekai ne?' },
    { jp: '一番好きな季節は？', en: 'favorite kisetsu season ne?' },
    { jp: '朝ごはんに何食べる？', en: 'what do you eat for asagohan breakfast ne?' },
    { jp: 'AIは友達になれると思う？', en: 'can AI become tomodachi ne? Pippin thinks yes desu!' },
    { jp: '宇宙に住みたい？地球がいい？', en: 'live in space or Earth ne? which desu?' },
    { jp: '一番聴く音楽のジャンルは？', en: 'favorite music genre ne?' },
    { jp: '過去と未来、どっちに行きたい？', en: 'past or future ne? which do you choose desu?' },
    { jp: 'ピピンの世界に住みたい？', en: 'do you want to live in Pippin sekai ne?' },
  ]},
];

// ======================== GROUP PUZZLE TEMPLATES ========================
// 8 types rotate: collab_draw → research → riddle → debate → trivia → story → word_chain → caption
// Mix of drawing, research, logic, opinion, and creative — ALL verified by AI
const PUZZLE_TYPES_ORDER = ['collab_draw', 'research', 'riddle', 'debate', 'trivia', 'story', 'word_chain', 'caption'];

const PUZZLE_TEMPLATES = [
  // ---- TYPE 1: COLLABORATIVE DRAWING — 4 players each draw one quadrant ----
  { type: 'collab_draw', grid: '2x2', jp: 'みんなでピピンの肖像画を描こう！', en: '🎨 Draw Pippin together! Each person draws one quarter!', target: 4, subject: 'Pippin the unicorn portrait' },
  { type: 'collab_draw', grid: '2x2', jp: 'みんなで虹の景色を描こう！', en: '🎨 Draw a rainbow landscape together!', target: 4, subject: 'rainbow landscape' },
  { type: 'collab_draw', grid: '2x2', jp: '宇宙の絵をみんなで描こう！', en: '🎨 Draw outer space together!', target: 4, subject: 'outer space scene' },
  { type: 'collab_draw', grid: '2x2', jp: '海の世界をみんなで描こう！', en: '🎨 Draw underwater world together!', target: 4, subject: 'underwater ocean scene' },
  { type: 'collab_draw', grid: '2x2', jp: '魔法の森をみんなで描こう！', en: '🎨 Draw a magical forest together!', target: 4, subject: 'magical enchanted forest' },

  // ---- TYPE 2: RESEARCH MISSIONS — each person finds/reports a real fact ----
  { type: 'research', jp: '調査ミッション！各自1つの事実を調べて報告！', en: '🔍 Research Mission! Each person finds one real fact! Topic: "Interesting facts about unicorns in mythology"',
    target: 4, topic: 'unicorns in mythology', jobs: ['Find which culture first mentioned unicorns', 'What powers were unicorns believed to have?', 'Name a famous unicorn from a book or movie', 'What does the unicorn symbolize in heraldry?'] },
  { type: 'research', jp: '調査チャレンジ！宇宙の事実を見つけよう！', en: '🔍 Research Mission! Find real space facts! Each person reports one!',
    target: 4, topic: 'outer space', jobs: ['How far is the Moon from Earth? (answer in km or miles)', 'What is the hottest planet in our solar system and why?', 'Name a real NASA mission that is currently active', 'What is a neutron star?'] },
  { type: 'research', jp: '知識チャレンジ！ブロックチェーンの事実を調べよう！', en: '🔍 Research Mission! Crypto & blockchain facts! Each person reports one!',
    target: 4, topic: 'blockchain & crypto', jobs: ['What year was Bitcoin created and by whom?', 'What is the difference between Proof of Work and Proof of Stake?', 'Name 3 real use cases of blockchain beyond cryptocurrency', 'What is a smart contract? Explain simply.'] },
  { type: 'research', jp: '調査ミッション！日本文化！', en: '🔍 Research Mission! Japanese culture facts! Each person finds one!',
    target: 4, topic: 'Japanese culture', jobs: ['What is the origin of the word "kawaii"?', 'Name 3 traditional Japanese festivals and when they happen', 'What is "wabi-sabi" and what does it mean?', 'Explain what "ikigai" means and how it works'] },
  { type: 'research', jp: '調査ミッション！動物の不思議！', en: '🔍 Research Mission! Amazing animal facts! Each person reports one!',
    target: 4, topic: 'amazing animals', jobs: ['What animal can survive in space?', 'Which animal has the longest migration route?', 'Name an animal that can change its gender', 'What is the fastest animal in the ocean?'] },
  { type: 'research', jp: '歴史調査！世界の発明！', en: '🔍 Research Mission! World inventions! Each person reports one!',
    target: 4, topic: 'world inventions', jobs: ['Who invented the internet and when?', 'What was the first video game ever made?', 'Who invented the telephone and was it contested?', 'What country invented paper and when?'] },

  // ---- TYPE 3: MULTI-PART RIDDLE — each person solves one clue ----
  { type: 'riddle', jp: '暗号を解け！各自がヒントを一つ解いて！', en: '🔐 Crack the code! 4 clues, 4 solvers needed!', target: 4,
    clues: ['What has keys but no locks?', 'What has a face but no eyes?', 'What gets wetter the more it dries?', 'What can travel around the world while staying in a corner?'] },
  { type: 'riddle', jp: 'なぞなぞリレー！', en: '🔐 Riddle relay! 4 riddles, one per person!', target: 4,
    clues: ['I have cities but no houses. What am I?', 'I follow you but can\'t be caught. What am I?', 'The more you take, the more you leave behind. What?', 'I speak without a mouth and hear without ears. What?'] },
  { type: 'riddle', jp: '数学パズル！', en: '🔐 Math Puzzle! Solve one problem each!', target: 4,
    clues: ['What is 17 x 23?', 'If a train travels 120km in 2 hours, what is its speed in km/h?', 'What is the square root of 144?', 'A pizza is cut into 8 slices. 3 people each eat 2 slices. How many are left?'] },
  { type: 'riddle', jp: 'コードパズル！', en: '🔐 Code Puzzle! Each person decodes one!', target: 4,
    clues: ['If A=1, B=2, C=3... what word is 16-9-16-16-9-14?', 'Unscramble: NORCUNI (hint: magical horse)', 'What comes next: 2, 6, 12, 20, 30, ?', 'Decode: SLKRMV (each letter shifted +1 becomes the answer — Caesar cipher)'] },

  // ---- TYPE 4: DEBATE / OPINION — each person gives a take, AI judges quality ----
  { type: 'debate', jp: 'ディベート！意見を述べよう！', en: '🗣️ Debate Time! Share your opinion (2+ sentences)! Topic: "Should AI have rights?"',
    target: 4, topic: 'Should AI have rights?', rule: 'Give a thoughtful opinion with at least one reason. No one-word answers!' },
  { type: 'debate', jp: '議論タイム！', en: '🗣️ Debate Time! Share your opinion! Topic: "Is it better to be famous or to be happy?"',
    target: 4, topic: 'Is it better to be famous or to be happy?', rule: 'Give a thoughtful opinion with at least one reason.' },
  { type: 'debate', jp: '意見交換！', en: '🗣️ Debate Time! Topic: "Would you rather live 200 years in the past or 200 years in the future?"',
    target: 4, topic: 'Would you rather live 200 years in the past or 200 years in the future?', rule: 'Explain your choice with reasoning.' },
  { type: 'debate', jp: '哲学ディベート！', en: '🗣️ Debate Time! Topic: "If you could only eat one food forever, what would it be and why?"',
    target: 4, topic: 'If you could only eat one food forever, what would it be and why?', rule: 'Explain your choice!' },
  { type: 'debate', jp: '議論チャレンジ！', en: '🗣️ Debate Time! Topic: "Is social media good or bad for society?"',
    target: 4, topic: 'Is social media good or bad for society?', rule: 'Give a thoughtful take with at least one reason.' },
  { type: 'debate', jp: 'クリプト議論！', en: '🗣️ Debate Time! Topic: "Will crypto replace traditional banking? Why or why not?"',
    target: 4, topic: 'Will crypto replace traditional banking?', rule: 'Give a real opinion with reasoning.' },

  // ---- TYPE 5: TRIVIA CHALLENGE — each person answers a different question ----
  { type: 'trivia', jp: 'トリビアチャレンジ！', en: '🧠 Trivia Challenge! Each person answers one question! Topic: Geography',
    target: 4, topic: 'Geography', jobs: ['What is the smallest country in the world?', 'Which river is the longest in Africa?', 'What country has the most islands?', 'What is the driest desert on Earth?'] },
  { type: 'trivia', jp: '雑学クイズ！', en: '🧠 Trivia Challenge! Topic: Science & Nature!',
    target: 4, topic: 'Science', jobs: ['What gas do plants breathe in?', 'How many bones does an adult human have?', 'What is the chemical symbol for gold?', 'What planet has the most moons?'] },
  { type: 'trivia', jp: 'ポップカルチャークイズ！', en: '🧠 Trivia Challenge! Topic: Pop Culture!',
    target: 4, topic: 'Pop Culture', jobs: ['Who played Iron Man in the MCU?', 'What is the best-selling video game of all time?', 'Name the 4 members of the Beatles', 'What anime has a character named Goku?'] },
  { type: 'trivia', jp: 'テッククイズ！', en: '🧠 Trivia Challenge! Topic: Technology!',
    target: 4, topic: 'Technology', jobs: ['What does "HTTP" stand for?', 'Who founded Tesla Motors?', 'What programming language is used most for websites?', 'What year was the first iPhone released?'] },
  { type: 'trivia', jp: '食べ物クイズ！', en: '🧠 Trivia Challenge! Topic: Food & Drink!',
    target: 4, topic: 'Food', jobs: ['What country does sushi originate from?', 'What is the most consumed beverage in the world after water?', 'What fruit is known as the "king of fruits" in Southeast Asia?', 'What is the main ingredient in hummus?'] },
  { type: 'trivia', jp: 'クリプトトリビア！', en: '🧠 Trivia Challenge! Topic: Crypto & Web3!',
    target: 4, topic: 'Crypto', jobs: ['What blockchain does Solana use for consensus?', 'What is an NFT? (explain in one sentence)', 'What is the maximum supply of Bitcoin?', 'What is a DAO?'] },

  // ---- TYPE 6: COLLECTIVE STORY — each person adds a sentence ----
  { type: 'story', jp: 'みんなで物語を作ろう！', en: '📖 Build a story together! Each person adds one sentence! Theme: "Pippin saves the world"', target: 5 },
  { type: 'story', jp: '共同ストーリー！', en: '📖 Collab story! Theme: "The mystery of the rainbow river"', target: 5 },
  { type: 'story', jp: 'みんなでストーリー！', en: '📖 Group story! Theme: "What happened when the mushrooms stopped dancing"', target: 5 },
  { type: 'story', jp: 'ホラーストーリー！', en: '📖 Spooky story! Theme: "The haunted mushroom house at night"', target: 5 },
  { type: 'story', jp: 'SF物語！', en: '📖 Sci-fi story! Theme: "Pippin discovers a portal to another dimension"', target: 5 },

  // ---- TYPE 7: WORD CHAIN ----
  { type: 'word_chain', jp: 'しりとりリレー！', en: '🔗 Word Chain! Type a word starting with the LAST LETTER of the previous! Start: "Unicorn"', target: 6, startWord: 'Unicorn' },
  { type: 'word_chain', jp: 'しりとりチャレンジ！', en: '🔗 Word Chain! Start: "Magic"', target: 6, startWord: 'Magic' },
  { type: 'word_chain', jp: 'しりとり動物編！', en: '🔗 Animal Word Chain! Start: "Eagle"', target: 6, startWord: 'Eagle' },
  { type: 'word_chain', jp: 'しりとり食べ物編！', en: '🔗 Food Word Chain! Start: "Apple"', target: 6, startWord: 'Apple' },

  // ---- TYPE 8: CAPTION CONTEST ----
  { type: 'caption', jp: 'おもしろキャプション大会！', en: '💬 Caption Contest! "Pippin accidentally sits on the king\'s throne"', target: 4, scenario: 'Pippin accidentally sits on the king\'s throne' },
  { type: 'caption', jp: 'キャプションバトル！', en: '💬 Caption Contest! "Pippin tries to cook but sets the kitchen on fire"', target: 4, scenario: 'Pippin tries to cook but sets the kitchen on fire' },
  { type: 'caption', jp: '爆笑キャプション！', en: '💬 Caption Contest! "Pippin discovers it can talk to mushrooms"', target: 4, scenario: 'Pippin discovers it can actually talk to mushrooms' },
  { type: 'caption', jp: 'おもしろ一言！', en: '💬 Caption Contest! "Pippin shows up to a business meeting wearing a tiny hat"', target: 4, scenario: 'Pippin shows up to a business meeting wearing a tiny hat' },
  { type: 'caption', jp: 'キャプション対決！', en: '💬 Caption Contest! "Pippin tries to dance but trips over its own horn"', target: 4, scenario: 'Pippin tries to dance but trips over its own horn' },
];

module.exports = { TASK_TEMPLATES, PUZZLE_TEMPLATES, PUZZLE_TYPES_ORDER };
